"""Generate the Phase-3c diagnostics micro-session (pinned A100-40GB).

Four small corner groups that settle the open sanity questions before the
decision guide / write-up, bundled into ONE from-scratch Colab session so
the setup overhead (venv + checkpoint restore) is paid once. 9 cells, 4
server launches, ~1.5-2h. Block name `diagnostics`: excluded from the
factorial and k_stress analyses by their block filters.

1. tau-eager-short (2 cells, c1 x reps {0,1}): EAGLE-3 in EAGER mode on
   SHORT GSM8K prompts (workload mirrors the factorial's gsm8k cells:
   64 requests, 8-shot, 256 new tokens; server byte-identical to the
   k_stress probe's fp16kv corner). Settles whether the probe's tau~1.14
   is a long-context finding or an eager-mode artifact:
   tau ~ 2.85 here => eager innocent, context is the cause (finding real);
   tau << 2.85 here => eager artifact, the probe's tau story needs rework.

2. slong-eager-base (4 cells, c{1,8} x reps {0,1}): the NO-SPEC eager
   baseline at long context the probe lacks. Same server flags as the
   probe minus the speculative config, same 7.4k-token RAG workload.
   Enables the S-main-at-long-context measurement WITHIN the eager
   regime: probe S+fp16kv goodput (34.0 @ c1 / 166.4 @ c8, results
   2026-07-15) vs this baseline. If baseline >= probe, EAGLE-3 is
   counterproductive at long context even at batch 1 -- the decision
   guide sentence tau=1.14 implies, measured instead of inferred.

3. cudagraph-probe (1 cell, c1 r0): the crashing probe corner with
   compilation ON but CUDA graphs OFF. Pins the vLLM 0.24.0 bug: crash
   here => compiled-kernel bug broadly; survives => bug is specifically
   CUDA-graph capture (`currentStreamCaptureStatusMayInitCtx` hint).
   EITHER OUTCOME IS THE DATA -- a `status: failed` record is success for
   this cell; do not retry it. Feeds the upstream vLLM issue, nothing
   else; its goodput is not comparable to anything.

4. backendpin-flashinfer (2 cells, c8 x reps {0,1}): FP16-KV capacity
   cell with the attention backend pinned to FLASHINFER (the backend
   FP8-KV cells select automatically). Bounds the backend-switch
   component inside every K contrast in the project: compare against the
   k_stress fp16kv c8 cells (FLASH_ATTN, ~221 tok/s goodput) -- the
   difference is backend, not KV precision.

Run from the repo root:  python3 configs/diagnostics/generate_diagnostics.py
"""
from __future__ import annotations

import pathlib

BASE_MODEL = "meta-llama/Llama-3.1-8B-Instruct"
EAGLE3_DRAFT = "yuhuili/EAGLE3-LLaMA3.1-Instruct-8B"

HEADER = """\
# Phase-3c diagnostics cell, generated by
# configs/diagnostics/generate_diagnostics.py. Edit the generator, never
# this file. A100-40GB (Colab High-RAM OFF), matching the Phase-3b cells
# these diagnostics are compared against.
block: diagnostics
# Explicit run_id: two diagnostic groups share identical factors (both
# no-spec fp16/fp16 RAG) and differ only in engine flags, which the
# derived run_id does not encode.
run_id: diag_%(tag)s_c%(conc)d_r%(rep)d
engine: vllm
model: %(model)s
factors:
  weight_quant: fp16
  kv_quant: fp16
  spec_decode: %(spec)s
%(draft_line)sworkload: %(workload)s
workload_params:
%(workload_params)s
concurrency: %(conc)d
decoding: greedy
seed: 1234
repeat_idx: %(rep)d
warmup_requests: 4
gpu_target: a100_40gb
engine_args:
  port: 8000
  dtype: float16
  gpu_memory_utilization: 0.85
  max_model_len: 8192
  enable_prefix_caching: false
  num_speculative_tokens: 5
%(engine_extra)s"""

# Mirrors the factorial's gsm8k cells so tau is directly comparable to the
# factorial S-corner reference (tau ~ 2.85 at c1).
GSM8K_PARAMS = """\
  num_requests: 64
  max_new_tokens: 256
  n_shot: 8
"""

# Mirrors the k_stress probe workload exactly (tokenizer-exact 7.4k docs).
def rag_params(num_requests: int) -> str:
    return """\
  num_requests: %d
  max_new_tokens: 256
  prefix_overlap: low
  doc_target_tokens: 7400
  tokenizer_model: meta-llama/Llama-3.1-8B-Instruct
  prompt_token_budget: 7900
  request_timeout_s: 1800
  spec_bench_file: external/Spec-Bench/data/spec_bench/question.jsonl
""" % num_requests


EAGER_EXTRA = """\
  # Same flag pair as the validated Phase-3b probe launch (PREREQ
  # 2026-07-15): eager sidesteps the compiled eagle_head crash and keeps
  # this cell in the SAME regime as the probe cells it is compared to.
  extra: ["--max-num-batched-tokens", "8192", "--enforce-eager"]
"""

CUDAGRAPH_OFF_EXTRA = """\
  # Bug bisection: compile ON, CUDA graphs OFF. A crash here means the
  # vLLM 0.24.0 defect is in the compiled kernels broadly; survival pins
  # it to CUDA-graph capture. status=failed is an INFORMATIVE outcome.
  extra: ["--max-num-batched-tokens", "8192", "--compilation-config", "{\\"cudagraph_mode\\": \\"NONE\\"}"]
"""

BACKEND_PIN_EXTRA = """\
  # Pin the backend FP8-KV cells select automatically; compare with the
  # k_stress fp16kv c8 cells (FLASH_ATTN) to bound the backend component
  # inside the project's K contrasts. Compiled, like those cells.
  env:
    VLLM_ATTENTION_BACKEND: FLASHINFER
"""

DRAFT_LINE = "draft_model: %s\n" % EAGLE3_DRAFT

# tag -> (spec, draft_line, workload, params_by_conc, engine_extra, concs, reps)
CORNERS = {
    "tau-eager-short": (
        "eagle3", DRAFT_LINE, "gsm8k",
        {1: GSM8K_PARAMS}, EAGER_EXTRA, (1,), (0, 1)),
    "slong-eager-base": (
        "none", "", "rag_shared_prefix",
        {1: rag_params(24), 8: rag_params(64)}, EAGER_EXTRA, (1, 8), (0, 1)),
    "cudagraph-probe": (
        "eagle3", DRAFT_LINE, "rag_shared_prefix",
        {1: rag_params(24)}, CUDAGRAPH_OFF_EXTRA, (1,), (0,)),
    "backendpin-flashinfer": (
        "none", "", "rag_shared_prefix",
        {8: rag_params(64)}, BACKEND_PIN_EXTRA, (8,), (0, 1)),
}


def main(out_dir=None) -> int:
    out_dir = pathlib.Path(out_dir) if out_dir else pathlib.Path(__file__).parent
    for stale in out_dir.glob("diag_*.yaml"):
        stale.unlink()
    count = 0
    for tag, (spec, draft_line, workload, params, extra, concs, reps) in CORNERS.items():
        for conc in concs:
            for rep in reps:
                text = HEADER % dict(
                    model=BASE_MODEL, spec=spec, draft_line=draft_line,
                    workload=workload, workload_params=params[conc].rstrip("\n"),
                    conc=conc, rep=rep, engine_extra=extra, tag=tag,
                )
                (out_dir / ("diag_%s_c%d_r%d.yaml" % (tag, conc, rep))).write_text(text)
                count += 1
    print("wrote %d configs to %s" % (count, out_dir))
    return count


if __name__ == "__main__":
    main()
