"""Generate the K-stress addendum cells: does FP8-KV relieve KV-cache
CAPACITY pressure? (Phase-3 addendum; redesigned for a pinned A100-40GB.)

Phase 2's K marginal was ~flat (0.94-1.03x) -- a real null for its regime:
demand peaked at ~18% of the KV pool, so K's capacity channel never engaged.
These cells create the pressure deliberately: unique ~7.4k-token documents
(prefix_overlap=low -- nothing shareable), FP16 weights, no spec decode.

CARD CHOICE (2026-07-09): Colab's High-RAM toggle pins the A100 variant
(off = 40GB, on = 80GB -- PREREQ_RESULTS Check 1). This experiment targets
the **40GB card (High-RAM OFF)** because both ceilings then fit inside a
small grid:

  pool ~= 0.85*40GB - ~16GB weights - overhead ~= 15-17 GB
       ~= ~120-135k FP16-KV tokens (128 KiB/token) or ~2x that under FP8
  per-request context ~= 7.4k prompt + 256 output ~= 7.7k tokens
  -> FP16-KV ceiling ~= 16 concurrent requests; FP8-KV ~= 32

Grid: {FP16-KV, FP8-KV} x concurrency {8, 16, 32, 48} x 2 repeats = 16
cells, 2 launches. Each level has a job:
  8  = below both ceilings (the Phase-2 null must reproduce here)
  16 = ON the predicted FP16 knee
  32 = FP16 saturated, ON the predicted FP8 knee (max divergence)
  48 = beyond both -- FP8's own plateau at ~2x FP16's is the money shot
       the 80GB design could never show inside a sane concurrency range.
Predictions are checked against the actual pool the server logs at startup
("GPU KV cache size: N tokens"); env.gpu_name is recorded per run.

The cube/factorial sessions are the opposite: they must run High-RAM ON
(80GB) to match the card Phase 2's marginal corners were measured on.

Run from the repo root:  python3 configs/k_stress/generate_k_stress.py
"""
from __future__ import annotations

import pathlib

BASE_MODEL = "meta-llama/Llama-3.1-8B-Instruct"

CONCURRENCY_REQUESTS = {8: 64, 16: 96, 32: 160, 48: 192}
REPEATS = (0, 1)  # large predicted effect; 2 repeats suffice (design review)
KV = {"fp16kv": "fp16", "fp8kv": "fp8"}

TEMPLATE = """\
# K-stress addendum cell, generated by configs/k_stress/generate_k_stress.py.
# Edit the generator, not this file. A100-40GB (Colab High-RAM OFF) -- the
# ceiling arithmetic in the generator docstring assumes the 40GB pool.
block: k_stress
engine: vllm
model: {model}
factors:
  weight_quant: fp16
  kv_quant: {kv}
  spec_decode: none
workload: rag_shared_prefix
workload_params:
  num_requests: {n}
  max_new_tokens: 256
  prefix_overlap: low
  doc_target_tokens: 7400
  request_timeout_s: 1800
  spec_bench_file: external/Spec-Bench/data/spec_bench/question.jsonl
concurrency: {conc}
decoding: greedy
seed: 1234
repeat_idx: {repeat}
warmup_requests: 4
gpu_target: a100_40gb
engine_args:
  port: 8000
  dtype: float16
  gpu_memory_utilization: 0.85
  max_model_len: 8192
  enable_prefix_caching: false
  num_speculative_tokens: 5
"""


def main() -> None:
    out_dir = pathlib.Path(__file__).parent
    for stale in out_dir.glob("kstress_*.yaml"):
        stale.unlink()
    count = 0
    for tag, kv in KV.items():
        for conc, n in CONCURRENCY_REQUESTS.items():
            for repeat in REPEATS:
                text = TEMPLATE.format(
                    model=BASE_MODEL, kv=kv, n=n, conc=conc, repeat=repeat,
                )
                name = "kstress_%s_c%d_r%d.yaml" % (tag, conc, repeat)
                (out_dir / name).write_text(text)
                count += 1
    print("wrote %d configs to %s" % (count, out_dir))


if __name__ == "__main__":
    main()
