"""Generate the K-stress addendum cells (Phase-3 addendum, design reviewed
2026-07-09): does FP8-KV relieve KV-cache CAPACITY pressure?

Phase 2's K marginal was ~flat (0.94-1.03x) -- a real null for its regime:
demand peaked at ~18% of the KV pool, so K's capacity channel never engaged.
This block creates the pressure deliberately: unique ~7.4k-token documents
(prefix_overlap=low, so demand = sum of full per-request contexts, nothing
shareable), FP16 weights, no spec -- {FP16-KV, FP8-KV} x concurrency
{32, 48, 64, 96} x 2 repeats = 16 cells, 2 server launches.

Ceiling arithmetic (Llama-3.1-8B: 128 KiB/token FP16-KV, 64 KiB FP8):
- A100-80GB (~46-48 GB KV pool): FP16 sustains ~47 concurrent 7.7k-token
  requests, FP8 ~94 -> divergence at conc 48/64/96; conc 32 is the
  below-ceiling control. The 48 level sits ON the predicted FP16 ceiling.
- A100-40GB (~14-16 GB pool): FP16 ~15, FP8 ~30 -> everything diverges.
Predictions are checked against the actual pool size the server logs at
startup ("GPU KV cache size: N tokens"); env.gpu_name is recorded per run.

Run from the repo root:  python3 configs/k_stress/generate_k_stress.py
"""
from __future__ import annotations

import pathlib

BASE_MODEL = "meta-llama/Llama-3.1-8B-Instruct"

CONCURRENCY_REQUESTS = {32: 160, 48: 192, 64: 256, 96: 320}
REPEATS = (0, 1)  # large predicted effect; 2 repeats suffice (design review)
KV = {"fp16kv": "fp16", "fp8kv": "fp8"}

TEMPLATE = """\
# K-stress addendum cell, generated by configs/k_stress/generate_k_stress.py.
# Edit the generator, not this file. Isolates the K factor under KV-cache
# capacity pressure (unique long documents; FP16 weights; no spec decode).
block: k_stress
engine: vllm
model: {model}
factors:
  weight_quant: fp16
  kv_quant: {kv}
  spec_decode: none
workload: rag_shared_prefix
workload_params:
  num_requests: {n}
  max_new_tokens: 256
  prefix_overlap: low
  doc_target_tokens: 7400
  request_timeout_s: 1800
  spec_bench_file: external/Spec-Bench/data/spec_bench/question.jsonl
concurrency: {conc}
decoding: greedy
seed: 1234
repeat_idx: {repeat}
warmup_requests: 4
gpu_target: a100
engine_args:
  port: 8000
  dtype: float16
  gpu_memory_utilization: 0.85
  max_model_len: 8192
  enable_prefix_caching: false
  num_speculative_tokens: 5
"""


def main() -> None:
    out_dir = pathlib.Path(__file__).parent
    for stale in out_dir.glob("kstress_*.yaml"):
        stale.unlink()
    count = 0
    for tag, kv in KV.items():
        for conc, n in CONCURRENCY_REQUESTS.items():
            for repeat in REPEATS:
                text = TEMPLATE.format(
                    model=BASE_MODEL, kv=kv, n=n, conc=conc, repeat=repeat,
                )
                name = "kstress_%s_c%d_r%d.yaml" % (tag, conc, repeat)
                (out_dir / name).write_text(text)
                count += 1
    print("wrote %d configs to %s" % (count, out_dir))


if __name__ == "__main__":
    main()
