"""Generate the FULL core-factorial config board (EXPERIMENT_MATRIX.md §1/§3).

All 8 corners of the 2^3 cube -- baseline, W, K, S, W+K, W+S, K+S, W+K+S --
x 3 workloads x concurrency {1,8,32,64} x repeats {0,1,2} = 288 run cells,
all routed to A100 (the GPU-confound correction: never split K across GPUs).

Which subset runs first is a BUDGET decision made at sweep time via file
globs, not a config-generation decision. The Phase-2 marginals runbook
selects the four single-factor corners at repeat 0:

    configs/factorial/cube_base_*_r0.yaml  cube_w_*_r0.yaml
    cube_k_*_r0.yaml  cube_s_*_r0.yaml            (48 cells)

num_requests scales with concurrency (EXPERIMENT_MATRIX §2): a fixed count
is too slow sequentially at conc=1 and too few batch waves at conc=64.

Run from the repo root:  python3 configs/factorial/generate_phase2.py
(Removes stale cube_*.yaml / p2_*.yaml before writing, so renames never
leave duplicate run_ids behind.)
"""
from __future__ import annotations

import itertools
import pathlib

BASE_MODEL = "meta-llama/Llama-3.1-8B-Instruct"          # anchor (PROJECT_SPEC §4.2)
AWQ_MODEL = "hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4"  # Check 3b
EAGLE3_DRAFT = "yuhuili/EAGLE3-LLaMA3.1-Instruct-8B"     # Check 3

REPEATS = (0, 1, 2)  # HARNESS_SPEC §9 (revised): report spread, not points

# tag -> (weight_quant on?, kv fp8 on?, eagle3 on?)
CORNERS = {
    "base": (False, False, False),
    "w":    (True, False, False),
    "k":    (False, True, False),
    "s":    (False, False, True),
    "wk":   (True, True, False),
    "ws":   (True, False, True),
    "ks":   (False, True, True),
    "wks":  (True, True, True),   # the full stack -- Check 6's confirmed config
}

CONCURRENCY_REQUESTS = {1: 64, 8: 160, 32: 320, 64: 512}

WORKLOAD_PARAMS = {
    "gsm8k": "  num_requests: {n}\n  max_new_tokens: 256\n  n_shot: 8\n",
    "humaneval": (
        "  num_requests: {n}\n  max_new_tokens: 512\n"
        "  tokenizer_model: {model}\n  run_correctness: true\n"
    ),
    "rag_shared_prefix": (
        "  num_requests: {n}\n  max_new_tokens: 256\n  prefix_overlap: high\n"
        "  spec_bench_file: external/Spec-Bench/data/spec_bench/question.jsonl\n"
    ),
}

TEMPLATE = """\
# Core-factorial cell '{tag}', generated by configs/factorial/generate_phase2.py.
# Edit the generator, not this file.
block: core_factorial
engine: vllm
model: {model}
factors:
  weight_quant: {w}
  kv_quant: {k}
  spec_decode: {s}
{draft_line}workload: {workload}
workload_params:
{wparams}concurrency: {conc}
decoding: greedy
seed: {seed}
repeat_idx: {repeat}
warmup_requests: 4
gpu_target: a100
engine_args:
  port: 8000
  dtype: float16
  gpu_memory_utilization: 0.85
  max_model_len: 8192
  enable_prefix_caching: false
  num_speculative_tokens: 5
"""


def main() -> None:
    out_dir = pathlib.Path(__file__).parent
    for stale in itertools.chain(out_dir.glob("cube_*.yaml"), out_dir.glob("p2_*.yaml")):
        stale.unlink()
    count = 0
    for tag, (w_on, k_on, s_on) in CORNERS.items():
        model = AWQ_MODEL if w_on else BASE_MODEL
        for workload, wparams_tpl in WORKLOAD_PARAMS.items():
            for conc, n in CONCURRENCY_REQUESTS.items():
                for repeat in REPEATS:
                    text = TEMPLATE.format(
                        tag=tag,
                        model=model,
                        w="w4a16" if w_on else "fp16",
                        k="fp8" if k_on else "fp16",
                        s="eagle3" if s_on else "none",
                        draft_line=("draft_model: %s\n" % EAGLE3_DRAFT) if s_on else "",
                        workload=workload,
                        wparams=wparams_tpl.format(n=n, model=model),
                        conc=conc,
                        # Seed stays fixed so repeats share a server launch
                        # (seed is part of the launch command / server
                        # signature). The workload stream is reshuffled per
                        # repeat via seed+repeat_idx inside run.py.
                        seed=1234,
                        repeat=repeat,
                    )
                    name = "cube_%s_%s_c%d_r%d.yaml" % (tag, workload, conc, repeat)
                    (out_dir / name).write_text(text)
                    count += 1
    print("wrote %d configs to %s" % (count, out_dir))


if __name__ == "__main__":
    main()
