"""Generate the Phase-2 config set: serving baseline + single-optimization
marginals (EXPERIMENT_MATRIX.md blocks 1-2, IMPLEMENTATION_PLAN.md Phase 2).

4 configs (baseline, W alone, K alone, S alone -- four corners of the 2^3
cube, labeled block=core_factorial so Phase 3 reuses them directly)
x 3 workloads x concurrency {1,8,32,64} = 48 run cells, repeat_idx=0.

num_requests scales with concurrency (EXPERIMENT_MATRIX §2): a fixed count
is too slow sequentially at conc=1 and too few batch waves at conc=64.

Run from the repo root:  python3 configs/factorial/generate_phase2.py
"""
from __future__ import annotations

import pathlib

BASE_MODEL = "meta-llama/Llama-3.1-8B-Instruct"          # anchor (PROJECT_SPEC §4.2)
AWQ_MODEL = "hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4"  # Check 3b
EAGLE3_DRAFT = "yuhuili/EAGLE3-LLaMA3.1-Instruct-8B"     # Check 3

# tag -> (model, weight_quant, kv_quant, spec_decode, draft)
CONFIGS = {
    "base":   (BASE_MODEL, "fp16", "fp16", "none", None),
    "w4a16":  (AWQ_MODEL, "w4a16", "fp16", "none", None),
    "fp8kv":  (BASE_MODEL, "fp16", "fp8", "none", None),   # emulated on A100 -- documented
    "eagle3": (BASE_MODEL, "fp16", "fp16", "eagle3", EAGLE3_DRAFT),
}

CONCURRENCY_REQUESTS = {1: 64, 8: 160, 32: 320, 64: 512}

WORKLOAD_PARAMS = {
    "gsm8k": "  num_requests: {n}\n  max_new_tokens: 256\n  n_shot: 8\n",
    "humaneval": (
        "  num_requests: {n}\n  max_new_tokens: 512\n"
        "  tokenizer_model: {model}\n  run_correctness: true\n"
    ),
    "rag_shared_prefix": (
        "  num_requests: {n}\n  max_new_tokens: 256\n  prefix_overlap: high\n"
        "  spec_bench_file: external/Spec-Bench/data/spec_bench/question.jsonl\n"
    ),
}

TEMPLATE = """\
# Phase-2 cell: {tag} marginal, generated by configs/factorial/generate_phase2.py.
# Edit the generator, not this file.
block: core_factorial
engine: vllm
model: {model}
factors:
  weight_quant: {w}
  kv_quant: {k}
  spec_decode: {s}
{draft_line}workload: {workload}
workload_params:
{wparams}concurrency: {conc}
decoding: greedy
seed: 1234
repeat_idx: 0
warmup_requests: 4
gpu_target: a100
engine_args:
  port: 8000
  dtype: float16
  gpu_memory_utilization: 0.85
  max_model_len: 8192
  enable_prefix_caching: false
  num_speculative_tokens: 5
"""


def main() -> None:
    out_dir = pathlib.Path(__file__).parent
    count = 0
    for tag, (model, w, k, s, draft) in CONFIGS.items():
        for workload, wparams_tpl in WORKLOAD_PARAMS.items():
            for conc, n in CONCURRENCY_REQUESTS.items():
                text = TEMPLATE.format(
                    tag=tag, model=model, w=w, k=k, s=s,
                    draft_line=("draft_model: %s\n" % draft) if draft else "",
                    workload=workload,
                    wparams=wparams_tpl.format(n=n, model=model),
                    conc=conc,
                )
                name = "p2_%s_%s_c%d.yaml" % (tag, workload, conc)
                (out_dir / name).write_text(text)
                count += 1
    print("wrote %d configs to %s" % (count, out_dir))


if __name__ == "__main__":
    main()
